# Spring boot application
spring:
  application:
    name: skynet-web-admin
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 9000

# Services Versions
services:
  ports:
    user: 8601
    chat: 8801
    blog: 8901
  versions:
    user:
      v1: 1.0.0
    chat:
      v1: 1.0.0
    blog:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  scan:
    basePackages: com.skynet.dipper.web.admin
  ## ApplicationConfig Bean
  application:
    id: skynet-web-admin
    name: skynet-web-admin
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
    simplified: false

# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true

management:
  server:
    port: 9001
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
  # Enables Dubbo All Endpoints
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  # 配置日志级别，方别调试
  logging:
    level:
      org.springframework.cloud.gateway: debug