# Spring boot application
spring:
  application:
    name: skynet-service-chat-consumer
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 8801

# Services Versions
services:
  versions:
    user:
      v1: 1.0.0
    redis:
      v1: 1.0.0
    chat:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  scan:
    basePackages: com.skynet.dipper.service.chat.consumer
  ## ApplicationConfig Bean
  application:
    id: skynet-service-chat-consumer
    name: skynet-service-chat-consumer
  ## ProtocolConfig Bean
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
    simplified: false
  protocols:
    dubbo:
      name: dubbo
      port: -1
      state: server
      serialization: kryo
    grpc:
      name: grpc
      port: -1

websocket:
  server:
    port: 8989


# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true

management:
  server:
    port: 8701
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
  # Enables Dubbo All Endpoints
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

